module.exports = {
  config: [
    { title: `销售类型`, prop: `FSTName` },
    { title: `预订单号`, prop: `FBillNo` },
    { title: `日期`, prop: `FDate` },
    { title: `经销商`, prop: `FDealerCode` },
    { title: `客户编码`, prop: `FCustCode` },
    { title: `客户名称`, prop: `FCusName` },
    { title: `税率`, prop: `FTaxRate` },
    { title: `制单人`, prop: `FBillerName` },
    { title: `审核人`, prop: `FVerifierName` },
    { title: `审核日期`, prop: `FVerifyDate` },
    { title: `状态`, prop: `FStatusName` },
    { title: `备注`, prop: `FRemark` },
    { title: `U8单号`, prop: `FU8BillNo` },
    { title: `行号`, prop: `FNo` },
    { title: `存货编码`, prop: `FInvCode` },
    { title: `存货名称`, prop: `FInvName` },
    { title: `存货规格`, prop: `FInStd` },
    { title: `单位`, prop: `FComInvUnitName` },
    { title: `数量`, prop: `FQty` },
    { title: `面价`, prop: `FPlanPrice` },
    { title: `含税单价`, prop: `FTaxPrice` },
    { title: `税额`, prop: `FTaxAmount` },
    { title: `折扣额`, prop: `FDisAmount` },
    { title: `价税合计`, prop: `FSum` },
    { title: `到货日期`, prop: `FRequestDate` },
    { title: `特价项目`, prop: `FProject` },
    { title: `分录备注`, prop: `FEntryRemark` },
    { title: `最终无税单价`, prop: `FPrice2` },
    { title: `最终无税金额`, prop: `FAmount2` },
    { title: `最终含税单价`, prop: `FTaxPrice2` },
    { title: `最终价税合计`, prop: `FSum2` }
  ]
};
